server.port=8091
spring.application.name=ORDER-SERVICE

spring.config.import=optional:configserver:http://localhost:8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/stockApplication?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.profiles.active=dev

jwt.secret=${JWT_SECRET:mySuperSecureJwtSecretKeyThatIsAtLeast32BytesLong12345}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

hooks.wallet.base-url=http://localhost:8088/api/wallets
hooks.portfolio.base-url=http://localhost:8087/api/portfolios
hooks.market.base-url=http://localhost:8089/api/market

order.evaluator.fixed-delay-ms=5000
order.outbox.fixed-delay-ms=3000
