# Development Environment Configuration
# Database Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Show SQL for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
