# Production Environment Configuration
# Database Initialization (disabled in production)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Hide SQL in production
spring.jpa.show-sql=false
